// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeJournal(arg1:string):Promise<main.AnalysisResult>;

export function AnalyzeJournalCloud(arg1:string,arg2:string):Promise<main.AnalysisResult>;

export function CheckCrisisMarkers(arg1:string):Promise<main.CrisisResult>;

export function DeleteEntry(arg1:number):Promise<string>;

export function GetEntries():Promise<Array<main.Entry>>;

export function SaveEntry(arg1:number,arg2:string,arg3:string,arg4:Array<string>):Promise<string>;
