// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeJournal(arg1) {
  return window['go']['main']['App']['AnalyzeJournal'](arg1);
}

export function AnalyzeJournalCloud(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeJournalCloud'](arg1, arg2);
}

export function AnalyzeJournalForEntry(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeJournalForEntry'](arg1, arg2);
}

export function CancelPullModel(arg1) {
  return window['go']['main']['App']['CancelPullModel'](arg1);
}

export function ChangeVaultPassword(arg1, arg2, arg3) {
  return window['go']['main']['App']['ChangeVaultPassword'](arg1, arg2, arg3);
}

export function CheckCrisisMarkers(arg1) {
  return window['go']['main']['App']['CheckCrisisMarkers'](arg1);
}

export function DeleteEntry(arg1) {
  return window['go']['main']['App']['DeleteEntry'](arg1);
}

export function DetectHardware() {
  return window['go']['main']['App']['DetectHardware']();
}

export function FindSimilarEntries(arg1, arg2, arg3) {
  return window['go']['main']['App']['FindSimilarEntries'](arg1, arg2, arg3);
}

export function GenerateEmbedding(arg1) {
  return window['go']['main']['App']['GenerateEmbedding'](arg1);
}

export function GetAnalysisAudit(arg1) {
  return window['go']['main']['App']['GetAnalysisAudit'](arg1);
}

export function GetEntries() {
  return window['go']['main']['App']['GetEntries']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetVaultStatus() {
  return window['go']['main']['App']['GetVaultStatus']();
}

export function IsOllamaRunning() {
  return window['go']['main']['App']['IsOllamaRunning']();
}

export function ListModels() {
  return window['go']['main']['App']['ListModels']();
}

export function LockVault() {
  return window['go']['main']['App']['LockVault']();
}

export function PullModel(arg1) {
  return window['go']['main']['App']['PullModel'](arg1);
}

export function ResetVault(arg1, arg2) {
  return window['go']['main']['App']['ResetVault'](arg1, arg2);
}

export function SaveEntry(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SaveEntry'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveSettings(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['SaveSettings'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function SetupVaultPassword(arg1, arg2) {
  return window['go']['main']['App']['SetupVaultPassword'](arg1, arg2);
}

export function UnlockVault(arg1) {
  return window['go']['main']['App']['UnlockVault'](arg1);
}
