// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeJournal(arg1) {
  return window['go']['main']['App']['AnalyzeJournal'](arg1);
}

export function AnalyzeJournalCloud(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeJournalCloud'](arg1, arg2);
}

export function GetEntries() {
  return window['go']['main']['App']['GetEntries']();
}

export function SaveEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveEntry'](arg1, arg2, arg3, arg4);
}
