// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeJournal(arg1:string):Promise<main.AnalysisResult>;

export function AnalyzeJournalCloud(arg1:string,arg2:string):Promise<main.AnalysisResult>;

export function GetEntries():Promise<Array<main.Entry>>;

export function SaveEntry(arg1:string,arg2:string):Promise<string>;
