// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AnalyzeJournal(arg1:string):Promise<main.AnalysisResult>;

export function AnalyzeJournalCloud(arg1:string,arg2:string):Promise<main.AnalysisResult>;

export function AnalyzeJournalForEntry(arg1:string,arg2:number):Promise<main.AnalysisResult>;

export function CancelPullModel(arg1:string):Promise<boolean>;

export function ChangeVaultPassword(arg1:string,arg2:string,arg3:string):Promise<main.AuthResult>;

export function CheckCrisisMarkers(arg1:string):Promise<main.CrisisResult>;

export function DeleteEntry(arg1:number):Promise<string>;

export function DetectHardware():Promise<main.HardwareInfo>;

export function FindSimilarEntries(arg1:string,arg2:number,arg3:number):Promise<Array<main.Entry>>;

export function GenerateEmbedding(arg1:string):Promise<Array<number>>;

export function GetAnalysisAudit(arg1:number):Promise<Array<main.AnalysisAuditEvent>>;

export function GetEntries():Promise<Array<main.Entry>>;

export function GetSettings():Promise<main.Settings>;

export function GetVaultStatus():Promise<main.VaultStatus>;

export function IsOllamaRunning():Promise<boolean>;

export function ListModels():Promise<Array<string>>;

export function LockVault():Promise<main.AuthResult>;

export function PullModel(arg1:string):Promise<void>;

export function ResetVault(arg1:string,arg2:string):Promise<main.AuthResult>;

export function SaveEntry(arg1:number,arg2:string,arg3:string,arg4:Array<string>,arg5:string):Promise<string>;

export function SaveSettings(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:boolean):Promise<string>;

export function SetupVaultPassword(arg1:string,arg2:string):Promise<main.AuthResult>;

export function UnlockVault(arg1:string):Promise<main.AuthResult>;
